AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - my.app.graal::my-app-graal
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.handler
      Runtime: provided
      CodeUri: native-build/function.zip
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 1500
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyServiceApi
